const mapList = [
  { province: '安徽', mapName: 'anhui', contour: 'anhui-contour' },
  { province: '澳门', mapName: 'aomen', contour: 'aomen-contour' },
  { province: '北京', mapName: 'beijing', contour: 'beijing-contour' },
  { province: '重庆', mapName: 'chongqing', contour: 'chongqing-contour' },
  { province: '福建', mapName: 'fujian', contour: 'fujian-contour' },
  { province: '甘肃', mapName: 'gansu', contour: 'gansu-contour' },
  { province: '广东', mapName: 'guangdong', contour: 'guangdong-contour' },
  { province: '广西', mapName: 'guangxi', contour: 'guangxi-contour' },
  { province: '贵州', mapName: 'guizhou', contour: 'guizhou-contour' },
  { province: '海南', mapName: 'hainan', contour: 'hainan-contour' },
  { province: '河北', mapName: 'hebei', contour: 'hebei-contour' },
  { province: '黑龙江', mapName: 'heilongjiang', contour: 'heilongjiang-contour' },
  { province: '河南', mapName: 'henan', contour: 'henan-contour' },
  { province: '湖北', mapName: 'hubei', contour: 'hubei-contour' },
  { province: '湖南', mapName: 'hunan', contour: 'hunan-contour' },
  { province: '江苏', mapName: 'jiangsu', contour: 'jiangsu-contour' },
  { province: '江西', mapName: 'jiangxi', contour: 'jiangxi-contour' },
  { province: '吉林', mapName: 'jilin', contour: 'jilin-contour' },
  { province: '辽宁', mapName: 'liaoning', contour: 'liaoning-contour' },
  { province: '内蒙古', mapName: 'neimenggu', contour: 'neimenggu-contour' },
  { province: '宁夏', mapName: 'ningxia', contour: 'ningxia-contour' },
  { province: '青海', mapName: 'qinghai', contour: 'qinghai-contour' },
  { province: '山东', mapName: 'shandong', contour: 'shandong-contour' },
  { province: '上海', mapName: 'shanghai', contour: 'shanghai-contour' },
  { province: '山西', mapName: 'shanxi', contour: 'shanxi-contour' },
  { province: '陕西', mapName: 'shanxi1', contour: 'shanxi1-contour' },
  { province: '四川', mapName: 'sichuan', contour: 'sichuan-contour' },
  { province: '台湾', mapName: 'taiwan', contour: 'taiwan-contour' },
  { province: '天津', mapName: 'tianjin', contour: 'tianjin-contour' },
  { province: '香港', mapName: 'xianggang', contour: 'xianggang-contour' },
  { province: '新疆', mapName: 'xinjiang', contour: 'xinjiang-contour' },
  { province: '西藏', mapName: 'xizang', contour: 'xizang-contour' },
  { province: '云南', mapName: 'yunnan', contour: 'yunnan-contour' },
  { province: '浙江', mapName: 'zhejiang', contour: 'zhejiang-contour' }
]

export default mapList
